// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PhantomMask.Api.Data;

#nullable disable

namespace PhantomMask.Api.Migrations
{
    [DbContext(typeof(PhantomMaskDbContext))]
    partial class PhantomMaskDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PhantomMask.Api.Models.Masks", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("pharmaciesid")
                        .HasColumnType("int");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("stockQuantity")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("pharmaciesid");

                    b.ToTable("Masks");
                });

            modelBuilder.Entity("PhantomMask.Api.Models.Pharmacies", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal>("cashBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("openingHours")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Pharmacies");
                });

            modelBuilder.Entity("PhantomMask.Api.Models.PurchaseHistory", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("maskName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("masksId")
                        .HasColumnType("int");

                    b.Property<int>("pharmacyId")
                        .HasColumnType("int");

                    b.Property<string>("pharmacyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("transactionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("transactionDatetime")
                        .HasColumnType("datetime2");

                    b.Property<int>("transactionQuantity")
                        .HasColumnType("int");

                    b.Property<int>("usersid")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("usersid");

                    b.ToTable("PurchaseHistory");
                });

            modelBuilder.Entity("PhantomMask.Api.Models.Users", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal>("cashBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PhantomMask.Api.Models.Masks", b =>
                {
                    b.HasOne("PhantomMask.Api.Models.Pharmacies", "pharmacies")
                        .WithMany("masks")
                        .HasForeignKey("pharmaciesid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("pharmacies");
                });

            modelBuilder.Entity("PhantomMask.Api.Models.PurchaseHistory", b =>
                {
                    b.HasOne("PhantomMask.Api.Models.Users", "users")
                        .WithMany("purchaseHistories")
                        .HasForeignKey("usersid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("users");
                });

            modelBuilder.Entity("PhantomMask.Api.Models.Pharmacies", b =>
                {
                    b.Navigation("masks");
                });

            modelBuilder.Entity("PhantomMask.Api.Models.Users", b =>
                {
                    b.Navigation("purchaseHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
